language: python
python: 
  - "2.7"
install:
  - "sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib"
  - "sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib"
  - "pip install -r requirements.txt --use-mirrors"
before_script:
script:
  - "nosetests --with-doctest --with-coverage --cover-package=register"
