language: python
python: 
  - "2.7"
install:
  - "sudo apt-get -y install zlib1g-dev libjpeg8-dev"
  - "pip install -r requirements.txt --use-mirrors"
before_script:
script:
  - "nosetests --with-doctest --with-coverage --cover-package=register"
