language: python
python: 
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
before_script:
  - "sudo apt-get install zlib libjpeg"
script:
  - "nosetests --with-doctest --with-coverage --cover-package=register"
